// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opvqjjzhhntkwwbkomek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wdnFqanpoaG50a3d3YmtvbWVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzUzNDAsImV4cCI6MjA2NDUxMTM0MH0.Q_2OLCOOxYYYfEsBUFd4SUtNCFId2QGCJRj0j0y8VNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);